name: Laravel Package Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, mysql

    - name: Cache Composer Packages
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-git

    - name: Setup Laravel Application
      run: |
        composer create-project --prefer-dist laravel/laravel laravel_app --no-interaction
        cd laravel_app
        composer require devdojo/auth:dev-main --with-all-dependencies

    - name: Set Working Directory
      run: echo "Change directory context to Laravel app"
      working-directory: ./laravel_app

    - name: Update Package
      run: composer update devdojo/auth:dev-main
      working-directory: ./laravel_app

    - name: Run Migrations
      run: php artisan migrate
      working-directory: ./laravel_app

    - name: Run Tests
      run: ./vendor/bin/pest
      working-directory: ./laravel_app
